all:
  children:
    mlag_switches:
      hosts:
        sw3:
          ansible_host: 172.20.20.13
          mlag_local_ip: 10.255.255.1 # from subnet /30
          mlag_peer_ip: 10.255.255.2
        sw4:
          ansible_host: 172.20.20.14
          mlag_local_ip: 10.255.255.2
          mlag_peer_ip: 10.255.255.1

    sw1_group:
      hosts:
        sw1:
          ansible_host: 172.20.20.11
