---
- name: mlag on sw3 and sw4
  hosts: mlag_switches # runs basically the following tasks on the defined switches in hosts
  gather_facts: false
  roles:
    - peer_setup
    - ports

- name: sw1 uplink bundle
  hosts: sw1_group
  gather_facts: false
  roles:
    - sw1_uplink
